// data/tours.ts dosyasının yeni, zenginleştirilmiş hali

export interface Tour {
  id: number;
  turAdi: string;
  kategori: 'Kültür' | 'Doğa' | 'Tatil' | 'Tarih' | 'Günübirlik';
  sehirler: string[];
  aciklama: string;
  sure: string;
  oneCikanGorsel: string;
  rehber: {
    isim: string;
    whatsapp: string;
  };
}

const ortakRehber = { isim: "Eren Ak", whatsapp: "905382504000" };

export const toursData: Tour[] = [
  { id: 1, turAdi: "Miço Kadınlar Plajı Turu", kategori: 'Günübirlik', sehirler: ["Kocaeli"], aciklama: "Günübirlik bir kaçamakla, sadece kadınlara özel Miço Plajı'nda denizin ve güneşin keyfini çıkarın. Huzur dolu bir gün sizi bekliyor.", sure: "Günübirlik", oneCikanGorsel: "/tours/mico-plaji.jpg", rehber: ortakRehber },
  { id: 2, turAdi: "Eskişehir Kültür Mozaiği", kategori: 'Günübirlik', sehirler: ["Eskisehir"], aciklama: "Modern şehir yaşamı ve tarihi dokunun birleştiği Eskişehir'de; Sazova Parkı, Masal Şatosu, Odunpazarı evleri ve Porsuk Çayı'nda gondol sefası.", sure: "Günübirlik", oneCikanGorsel: "/tours/eskisehir.jpg", rehber: ortakRehber },
  { id: 3, turAdi: "Büyük Güneydoğu Gurme ve Tarih Turu", kategori: 'Tarih', sehirler: ["Gaziantep", "Sanliurfa", "Mardin", "Diyarbakir"], aciklama: "Gaziantep'in eşsiz lezzetleri, Şanlıurfa'nın peygamberler mirası, Mardin'in taş konakları ve Diyarbakır'ın tarihi surları arasında unutulmaz bir yolculuk.", sure: "4 Gece / 6 Gün", oneCikanGorsel: "/tours/guneydogu.jpg", rehber: ortakRehber },
  { id: 4, turAdi: "Turistik Tuz Ekspresi ile Çankırı", kategori: 'Günübirlik', sehirler: ["Cankiri"], aciklama: "Trenle keyifli bir yolculukla başlayan bu turda, yerin altındaki Tuz Mağarası'nın büyüleyici ve şifalı atmosferini keşfedin.", sure: "Günübirlik", oneCikanGorsel: "/tours/cankiri.jpg", rehber: ortakRehber },
  { id: 5, turAdi: "İstanbul Büyükada Nostaljisi", kategori: 'Günübirlik', sehirler: ["Istanbul"], aciklama: "Tarihi köşkler, faytonlar ve eşsiz manzaralar arasında İstanbul'un en büyük Prens Adası'nda huzurlu ve nostaljik bir gün.", sure: "Günübirlik", oneCikanGorsel: "/tours/buyukada.jpg", rehber: ortakRehber },
  { id: 6, turAdi: "Lavanta Bahçeleri, Salda ve Pamukkale", kategori: 'Doğa', sehirler: ["Isparta", "Burdur", "Denizli"], aciklama: "Isparta'nın mor lavanta tarlalarında eşsiz fotoğraflar çekin, Türkiye'nin Maldivleri Salda Gölü'nde serinleyin ve Pamukkale'nin beyaz travertenlerinde yürüyün.", sure: "1 Gece / 2 Gün", oneCikanGorsel: "/tours/lavanta.jpg", rehber: ortakRehber },
  { id: 7, turAdi: "Büyük Karadeniz ve Batum Yaylalar Turu", kategori: 'Doğa', sehirler: ["Amasya", "Samsun", "Ordu", "Giresun", "Trabzon", "Rize", "Artvin"], aciklama: "Amasya'dan Batum'a, Sümela Manastırı'ndan Uzungöl'e, Ayder Yaylası'ndan Karagöl'e uzanan, yeşilin her tonunu göreceğiniz kapsamlı bir macera.", sure: "4 Gece / 5 Gün", oneCikanGorsel: "/tours/karadeniz.jpg", rehber: ortakRehber },
  { id: 8, turAdi: "Olympos, Adrasan ve Kekova Tekne Turu", kategori: 'Tatil', sehirler: ["Antalya"], aciklama: "Antik Olympos'un bohem ruhu, Adrasan'ın sakinliği ve batık şehir Kekova'ya yapılan tekne turlarıyla Akdeniz'in en güzel koylarında tatil keyfi.", sure: "3 Gece / 4 Gün", oneCikanGorsel: "/tours/olympos.jpg", rehber: ortakRehber },
  { id: 9, turAdi: "Yozgat Günübirlik Anadolu Gezisi", kategori: 'Günübirlik', sehirler: ["Yozgat"], aciklama: "Bozkırın kalbinde yer alan Yozgat'ın tarihi konaklarını, Çamlık Milli Parkı'nı ve yöresel kültürünü keşfedeceğiniz sakin bir Anadolu gezisi.", sure: "Günübirlik", oneCikanGorsel: "/tours/yozgat.jpg", rehber: ortakRehber },
  { id: 10, turAdi: "İstanbul Manzaraları Turu", kategori: 'Günübirlik', sehirler: ["Istanbul"], aciklama: "Çamlıca Camii ve Kulesi'nden panoramik İstanbul, Beykoz Cam Müzesi'nin zarafeti, Yuşa Tepesi'nin manevi huzuru ve Boğaz'da tekne turu.", sure: "Günübirlik", oneCikanGorsel: "/tours/istanbul.jpg", rehber: ortakRehber },
  { id: 11, turAdi: "Bozcaada - Cunda Adası Tatili", kategori: 'Tatil', sehirler: ["Canakkale", "Balikesir"], aciklama: "Çanakkale'den Assos ve Behramkale'ye, oradan Cunda'nın taş sokaklarına ve Şeytan Sofrası'nın manzarasına uzanan dolu dolu bir Ege kaçamağı.", sure: "2 Gece / 3 Gün", oneCikanGorsel: "/tours/bozcaada.jpg", rehber: ortakRehber },
  { id: 12, turAdi: "Kapadokya Balon Turu", kategori: 'Kültür', sehirler: ["Nevsehir", "Kayseri"], aciklama: "Peri bacalarının üzerinde sıcak hava balonuyla süzülün, yer altı şehirlerini keşfedin ve Avanos'un çömlek atölyelerinde sanata tanıklık edin.", sure: "1 Gece / 2 Gün", oneCikanGorsel: "/tours/kapadokya.jpg", rehber: ortakRehber },
  { id: 13, turAdi: "Kıbrıs Kültür Turu (Uçaklı)", kategori: 'Kültür', sehirler: [], aciklama: "Uçak konforuyla yavru vatana yolculuk. Girne, Lefkoşa ve Gazimağusa'nın tarihi ve kültürel zenginliklerini Beşparmak Dağları manzarasıyla keşfedin.", sure: "3 Gece / 4 Gün", oneCikanGorsel: "/tours/kibris.jpg", rehber: ortakRehber },
  { id: 14, turAdi: "Çanakkale Şehitlik ve Tarihe Saygı Turu", kategori: 'Günübirlik', sehirler: ["Canakkale"], aciklama: "Seyit Onbaşı Tabyası, Şehitler Abidesi, 57. Alay Şehitliği ve Conkbayırı'nı ziyaret ederek tarihin yazıldığı topraklarda şanlı ecdadımıza bir vefa yolculuğu.", sure: "Günübirlik", oneCikanGorsel: "/tours/canakkale.jpg", rehber: ortakRehber },
  { id: 15, turAdi: "Kastamonu - Sinop Karadeniz Kaçamağı", kategori: 'Doğa', sehirler: ["Kastamonu", "Sinop"], aciklama: "Küre Dağları'nın yeşilini ve Sinop'un tarihi hapishanesini birleştiren, Karadeniz'in batı ucunda keyifli bir hafta sonu turu.", sure: "1 Gece / 2 Gün", oneCikanGorsel: "/tours/kastamonu-sinop.jpg", rehber: ortakRehber },
  { id: 16, turAdi: "Edirne Kakava Şenlikleri ve Hıdırellez", kategori: 'Günübirlik', sehirler: ["Edirne"], aciklama: "Baharın gelişini, Romanların coşkulu Kakava ateşleri ve eğlenceleriyle Edirne'de karşılayın, Hıdırellez coşkusunu yaşayın.", sure: "Günübirlik", oneCikanGorsel: "/tours/edirne.jpg", rehber: ortakRehber },
  { id: 17, turAdi: "Popüler Ege Turu: Alaçatı, Sığacık, Şirince", kategori: 'Tatil', sehirler: ["Izmir"], aciklama: "Alaçatı'nın renkli sokakları, Sığacık'ın sakin kalesi, Şirince'nin otantik atmosferi ve Kuşadası'nın enerjisi bir arada.", sure: "2 Gece / 3 Gün", oneCikanGorsel: "/tours/alacati.jpg", rehber: ortakRehber },
  { id: 18, turAdi: "Pamukkale Termal Otel Tatili", kategori: 'Tatil', sehirler: ["Denizli"], aciklama: "Pam Thermal Hotel'de 3 gece 4 gün konaklayarak, hem Pamukkale'nin beyaz travertenlerini keşfedin hem de termal suların şifasıyla yenilenin.", sure: "3 Gece / 4 Gün", oneCikanGorsel: "/tours/pamukkale.jpg", rehber: ortakRehber },
  { id: 19, turAdi: "Abant ve Gölcük Doğa Turu", kategori: 'Günübirlik', sehirler: ["Bolu"], aciklama: "Her mevsim ayrı bir güzelliğe bürünen Abant ve Gölcük göllerinin etrafında doğa yürüyüşleri yapın, tertemiz havanın tadını çıkarın.", sure: "Günübirlik", oneCikanGorsel: "/tours/abant.jpg", rehber: ortakRehber },
  { id: 20, turAdi: "Bursa Tarih ve Lezzet Turu", kategori: 'Günübirlik', sehirler: ["Bursa"], aciklama: "Osmanlı'nın ilk başkentinde Orhan Gazi ve Osman Gazi türbeleri, Ulu Cami, Kapalı Çarşı ve Cumalıkızık'ın otantik dokusunu bir günde yaşayın.", sure: "Günübirlik", oneCikanGorsel: "/tours/bursa.jpg", rehber: ortakRehber },
  { id: 21, turAdi: "Doğu Ekspresi ile Kars Macerası", kategori: 'Tarih', sehirler: ["Kirikkale", "Kayseri", "Sivas", "Erzincan", "Erzurum", "Kars"], aciklama: "Kışın bembeyaz manzaralar eşliğinde, Ankara'dan Kars'a uzanan Türkiye'nin en popüler ve nostaljik tren yolculuğu deneyimi.", sure: "1 Gece Tren / 2 Gün", oneCikanGorsel: "/tours/dogu-ekspresi.jpg", rehber: ortakRehber },
  { id: 22, turAdi: "Konya Mistik ve Kültürel Gezi", kategori: 'Günübirlik', sehirler: ["Konya"], aciklama: "Mevlana Müzesi'nde manevi bir yolculuğa çıkın, Kelebekler Vadisi'nde renklerin dansını izleyin ve Selçuklu'nun başkentinin izlerini sürün.", sure: "Günübirlik", oneCikanGorsel: "/tours/konya.jpg", rehber: ortakRehber },
  { id: 23, turAdi: "Safranbolu ve Amasra Hafta Sonu Turu", kategori: 'Tarih', sehirler: ["Karabuk", "Bartin"], aciklama: "UNESCO Dünya Mirası Safranbolu'nun tarihi konaklarında zamanda yolculuk yapın ve Fatih'in 'Çeşm-i Cihan'ı Amasra'nın güzelliğine tanıklık edin.", sure: "1 Gece / 2 Gün", oneCikanGorsel: "/tours/safranbolu.jpg", rehber: ortakRehber },
  { id: 24, turAdi: "Marmaris ve Akyaka Tekne Turu Tatili", kategori: 'Tatil', sehirler: ["Mugla"], aciklama: "Marmaris ve Akyaka'nın cennet koylarında tekne turlarıyla denizin ve güneşin tadını çıkarın, konforlu bir konaklama ile tatilinizi taçlandırın.", sure: "3 Gece / 4 Gün", oneCikanGorsel: "/tours/marmaris.jpg", rehber: ortakRehber },
  { id: 25, turAdi: "Ege'nin Saklı Köyleri Turu", kategori: 'Kültür', sehirler: ["Izmir"], aciklama: "Urla'nın sanat dolu sokakları, Türkiye'nin ilk 'Slow Food' köyü Germiyan, Bademler ve Alaçatı'yı içeren otantik bir Ege keşfi.", sure: "2 Gece / 3 Gün", oneCikanGorsel: "/tours/ege-koyleri.jpg", rehber: ortakRehber },
  { id: 26, turAdi: "İstanbul Selatin Camileri Turu", kategori: 'Günübirlik', sehirler: ["Istanbul"], aciklama: "Asya'nın en büyüğü Çamlıca Camii başta olmak üzere, İstanbul'un manevi atmosferini yansıtan sultanlar tarafından yaptırılmış selatin camilerini ziyaret edin.", sure: "Günübirlik", oneCikanGorsel: "/tours/istanbul-camiler.jpg", rehber: ortakRehber },
];